// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WriterApp.Data;

#nullable disable

namespace BlazorApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260127063718_AddAiActionHistory")]
    partial class AddAiActionHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("WriterApp.Data.AI.AiActionAppliedEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AppliedToDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AppliedToPageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AppliedToSectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HistoryEntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppliedAt");

                    b.HasIndex("HistoryEntryId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("AiActionAppliedEvents");
                });

            modelBuilder.Entity("WriterApp.Data.AI.AiActionHistoryEntryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionKey");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DocumentId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("AiActionHistoryEntries");
                });

            modelBuilder.Entity("WriterApp.Data.Documents.DocumentOutlineRecord", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outline")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentId");

                    b.ToTable("DocumentOutlines");
                });

            modelBuilder.Entity("WriterApp.Data.Documents.DocumentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("WriterApp.Data.Documents.PageNoteRecord", b =>
                {
                    b.Property<Guid>("PageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PageId");

                    b.ToTable("PageNotes");
                });

            modelBuilder.Entity("WriterApp.Data.Documents.PageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("SectionId", "OrderIndex");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("WriterApp.Data.Documents.SectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NarrativePurpose")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "OrderIndex");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("WriterApp.Data.Subscriptions.Plan", b =>
                {
                    b.Property<Guid>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlanId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            PlanId = new Guid("5f4d2c6f-98fd-4a26-9c0f-0a2a1f2d7c4b"),
                            IsActive = true,
                            Key = "free",
                            Name = "Free"
                        },
                        new
                        {
                            PlanId = new Guid("83d8f8f0-6d2f-4d68-b7df-4192dce1a6f5"),
                            IsActive = true,
                            Key = "standard",
                            Name = "Standard"
                        },
                        new
                        {
                            PlanId = new Guid("6d1d34ef-2a0f-4b24-8b3f-7f3f4a4b9f0b"),
                            IsActive = true,
                            Key = "professional",
                            Name = "Professional"
                        });
                });

            modelBuilder.Entity("WriterApp.Data.Subscriptions.PlanEntitlement", b =>
                {
                    b.Property<Guid>("PlanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlanId", "Key");

                    b.ToTable("PlanEntitlements");

                    b.HasData(
                        new
                        {
                            PlanId = new Guid("5f4d2c6f-98fd-4a26-9c0f-0a2a1f2d7c4b"),
                            Key = "ai.enabled",
                            Value = "false"
                        },
                        new
                        {
                            PlanId = new Guid("83d8f8f0-6d2f-4d68-b7df-4192dce1a6f5"),
                            Key = "ai.enabled",
                            Value = "true"
                        },
                        new
                        {
                            PlanId = new Guid("6d1d34ef-2a0f-4b24-8b3f-7f3f4a4b9f0b"),
                            Key = "ai.enabled",
                            Value = "true"
                        },
                        new
                        {
                            PlanId = new Guid("5f4d2c6f-98fd-4a26-9c0f-0a2a1f2d7c4b"),
                            Key = "ai.monthly_tokens",
                            Value = "0"
                        },
                        new
                        {
                            PlanId = new Guid("83d8f8f0-6d2f-4d68-b7df-4192dce1a6f5"),
                            Key = "ai.monthly_tokens",
                            Value = "200000"
                        },
                        new
                        {
                            PlanId = new Guid("6d1d34ef-2a0f-4b24-8b3f-7f3f4a4b9f0b"),
                            Key = "ai.monthly_tokens",
                            Value = "1000000"
                        },
                        new
                        {
                            PlanId = new Guid("5f4d2c6f-98fd-4a26-9c0f-0a2a1f2d7c4b"),
                            Key = "export.pdf",
                            Value = "false"
                        },
                        new
                        {
                            PlanId = new Guid("83d8f8f0-6d2f-4d68-b7df-4192dce1a6f5"),
                            Key = "export.pdf",
                            Value = "true"
                        },
                        new
                        {
                            PlanId = new Guid("6d1d34ef-2a0f-4b24-8b3f-7f3f4a4b9f0b"),
                            Key = "export.pdf",
                            Value = "true"
                        },
                        new
                        {
                            PlanId = new Guid("5f4d2c6f-98fd-4a26-9c0f-0a2a1f2d7c4b"),
                            Key = "ai.images.cover",
                            Value = "false"
                        },
                        new
                        {
                            PlanId = new Guid("83d8f8f0-6d2f-4d68-b7df-4192dce1a6f5"),
                            Key = "ai.images.cover",
                            Value = "false"
                        },
                        new
                        {
                            PlanId = new Guid("6d1d34ef-2a0f-4b24-8b3f-7f3f4a4b9f0b"),
                            Key = "ai.images.cover",
                            Value = "true"
                        });
                });

            modelBuilder.Entity("WriterApp.Data.Subscriptions.UserPlanAssignment", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "PlanId");

                    b.HasIndex("PlanId");

                    b.ToTable("UserPlanAssignments");
                });

            modelBuilder.Entity("WriterApp.Data.Subscriptions.UserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            UserId = "seed-system",
                            CreatedUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "System"
                        });
                });

            modelBuilder.Entity("WriterApp.Data.Usage.UsageAggregate", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalCostMicros")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "PeriodStartUtc", "PeriodEndUtc", "Kind");

                    b.ToTable("UsageAggregates");
                });

            modelBuilder.Entity("WriterApp.Data.Usage.UsageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CostMicros")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UsageEvents");
                });

            modelBuilder.Entity("WriterApp.Data.Documents.DocumentOutlineRecord", b =>
                {
                    b.HasOne("WriterApp.Data.Documents.DocumentRecord", "Document")
                        .WithOne()
                        .HasForeignKey("WriterApp.Data.Documents.DocumentOutlineRecord", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("WriterApp.Data.AI.AiActionAppliedEventRecord", b =>
                {
                    b.HasOne("WriterApp.Data.AI.AiActionHistoryEntryRecord", "HistoryEntry")
                        .WithMany()
                        .HasForeignKey("HistoryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoryEntry");
                });

            modelBuilder.Entity("WriterApp.Data.Documents.PageNoteRecord", b =>
                {
                    b.HasOne("WriterApp.Data.Documents.PageRecord", "Page")
                        .WithOne()
                        .HasForeignKey("WriterApp.Data.Documents.PageNoteRecord", "PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("WriterApp.Data.Documents.PageRecord", b =>
                {
                    b.HasOne("WriterApp.Data.Documents.DocumentRecord", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WriterApp.Data.Documents.SectionRecord", "Section")
                        .WithMany("Pages")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("WriterApp.Data.Documents.SectionRecord", b =>
                {
                    b.HasOne("WriterApp.Data.Documents.DocumentRecord", "Document")
                        .WithMany("Sections")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("WriterApp.Data.Subscriptions.PlanEntitlement", b =>
                {
                    b.HasOne("WriterApp.Data.Subscriptions.Plan", "Plan")
                        .WithMany("Entitlements")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("WriterApp.Data.Subscriptions.UserPlanAssignment", b =>
                {
                    b.HasOne("WriterApp.Data.Subscriptions.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("WriterApp.Data.Documents.DocumentRecord", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("WriterApp.Data.Documents.SectionRecord", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("WriterApp.Data.Subscriptions.Plan", b =>
                {
                    b.Navigation("Entitlements");
                });
#pragma warning restore 612, 618
        }
    }
}
