using System;

namespace WriterApp.Application.Exporting
{
    public sealed record ExportTemplateDto(
        Guid Id,
        string Name,
        string? PresetKey,
        int PageWidthMm,
        int PageHeightMm,
        int MarginTopMm,
        int MarginRightMm,
        int MarginBottomMm,
        int MarginLeftMm,
        string FontFamily,
        int BodyFontSizePt,
        decimal LineHeight,
        int ParagraphSpacingPt,
        bool HeaderEnabled,
        string? HeaderLeft,
        string? HeaderCenter,
        string? HeaderRight,
        bool FooterEnabled,
        string? FooterLeft,
        string? FooterCenter,
        string? FooterRight,
        bool PageNumbersEnabled,
        int PageNumberStart,
        bool TocEnabled,
        int TocDepth,
        DateTimeOffset CreatedAt,
        DateTimeOffset UpdatedAt);

    public sealed record ExportTemplateCreateRequest(
        string? Name,
        string? PresetKey,
        int PageWidthMm,
        int PageHeightMm,
        int MarginTopMm,
        int MarginRightMm,
        int MarginBottomMm,
        int MarginLeftMm,
        string? FontFamily,
        int BodyFontSizePt,
        decimal LineHeight,
        int ParagraphSpacingPt,
        bool HeaderEnabled,
        string? HeaderLeft,
        string? HeaderCenter,
        string? HeaderRight,
        bool FooterEnabled,
        string? FooterLeft,
        string? FooterCenter,
        string? FooterRight,
        bool PageNumbersEnabled,
        int PageNumberStart,
        bool TocEnabled,
        int TocDepth);

    public sealed record ExportTemplateUpdateRequest(
        string? Name,
        int PageWidthMm,
        int PageHeightMm,
        int MarginTopMm,
        int MarginRightMm,
        int MarginBottomMm,
        int MarginLeftMm,
        string? FontFamily,
        int BodyFontSizePt,
        decimal LineHeight,
        int ParagraphSpacingPt,
        bool HeaderEnabled,
        string? HeaderLeft,
        string? HeaderCenter,
        string? HeaderRight,
        bool FooterEnabled,
        string? FooterLeft,
        string? FooterCenter,
        string? FooterRight,
        bool PageNumbersEnabled,
        int PageNumberStart,
        bool TocEnabled,
        int TocDepth);
}
